## 出力層の設計

### 恒等関数とソフトマックス関数
分類では活性化関数用いたい。回帰では恒等関数を使う

$$
y_k = \frac{\exp(a_k)}{\sum_{i=1}^n \exp(a_i)}
$$

In [26]:
import numpy as np
#ソフトマックス関数の実装
a = np.array([0.3,2.9,4.0])
print(a)

[0.3 2.9 4. ]


In [27]:
exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [28]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [29]:
y = exp_a/sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [30]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [31]:
a2 = np.array([1.3,2.9,2.0])
y2 = softmax(a2)
print(y2)

[0.12552115 0.62171031 0.25276855]


### ソフトマックス関数の特徴
ベクトルの要素を全て足すと1になる

In [32]:
np.sum(y2) #3つの要素の和

1.0

In [33]:
y2 * 100 # 各カテゴリ(計3つ)にそれぞれ分類できる確率(%)を表す

array([12.5521146 , 62.17103063, 25.27685477])

### ソフトマックス関数の実装上の注意
expは、値が大きいと値が大きすぎてすぐにオーバーフローしてしまう。
なので、配列aが大きい場合は、計算途中にオーバーフローしないように調整する

In [34]:
a_big = np.array([1010,1000,900])
softmax(a_big)

/Users/xf9x/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([nan, nan, nan])

ベクトルの要素全てに同じ値を足しても、ソフトマックス関数の値は変化しない。
以下、すべての要素にCを足した場合の、k番目の要素が変わらないことの証明

$$
y_k' = \frac{\exp(a_k+C)}{\sum_{i=1}^n \exp(a_i+C)} \\
= \frac{\exp(C)\exp(a_k)}{\sum_{i=1}^n \exp(C)\exp(a_i)} \\
= \frac{\exp(C)\exp(a_k)}{\exp(C)\sum_{i=1}^n \exp(a_i)} \\
= \frac{\exp(a_k)}{\sum_{i=1}^n \exp(a_i)} \\
= y_k
$$

In [ ]:
c = np.max(a_big)
a_small = a_big - c
print(a_small)

In [42]:
softmax(a_small)

array([9.99954602e+01, 4.53978687e-03, 1.68883521e-46])

array([0.33333333, 0.33333333, 0.33333333])

In [57]:
def dummy_sigmoid(x):
    return 1/(1+pow(2,-x))

In [63]:
print(dummy_sigmoid(-100)) #ほぼ0
print(dummy_sigmoid(100))

7.888609052210118e-31
1.0
